# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: efficient_development
  pool: 5
  username: efficient
  password: efficient1

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: efficient_development
  pool: 5
  username: efficient
  password: efficient1

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: efficient_development
  pool: 5
  username: efficient
  password: efficient1
